ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
Vagrant.require_version ">= 2.0.0"

Vagrant.configure("2") do |config|
  config.ssh.forward_agent = true


  # CONFIGURE WEB SERVER (nginx)
  # 
  # set hostname, network, and aliases
    config.vm.define "node", primary: true do |node|
      node.vm.box = "charlle/node"
      node.vm.box_version = "1.5"
      node.ssh.username = "vagrant"
      node.vm.hostname = "node"
      node.vm.network :private_network, ip: '192.168.42.51'
      node.vm.network :forwarded_port, guest: 3000, host: 3000

    # SYNC FOLDERS 
    # 
    # node should be in /var/...
    # sync local with vm folders
      node.vm.synced_folder "app/", "/var/app/", type: "nfs"
      node.vm.synced_folder "config/", "/etc/nginx/sites-available/", type: "nfs"

    
    # SET RESOURCES
    #
    # box must have min 256MB and 25% CPU
    # set provider
      node.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", "25"]
        vb.memory = "256"
        vb.cpus = "1"
      end

    # START UP NGINX
    #  
    # restart nginx on guest after up
    node.trigger.after :up do |trigger|
      trigger.run_remote = {inline: "sudo service nginx restart"
      trigger.run_remote = {inline: "sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u vagrant --hp /home/vagrant"
      trigger.run_remote = {inline: "sudo pm2 start /var/app/app.js"
    end

  end
  #
  # END WEB SERVER (nginx)


# VAGRANT MESSAGE
  config.vm.post_up_message = "You're Node Server is Ready!"
end
