ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
Vagrant.require_version ">= 2.0.0"

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  config.ssh.forward_agent = true


# CONFIGURE NODE SERVER
# 
# set hostname, network, and aliases
  config.vm.define "node", primary: true do |node|
    node.ssh.username = "vagrant"
    node.vm.hostname = "node"
    node.vm.network :private_network, ip: '192.168.42.51'
    node.vm.network :forwarded_port, guest: 3000, host: 3000

  # SYNC FOLDERS 
  # 
  # node apps should be in /var/www...
  # sync local with vm folders
    node.vm.synced_folder "../app/", "/var/www/", type: "nfs"
    node.vm.synced_folder "../app/config/", "/etc/nginx/sites-available/", type: "nfs"

  # SET RESOURCES
  #
  # box must have min 256MB and 25% CPU
  # set provider
    node.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--cpuexecutioncap", "25"]
      vb.memory = "256"
      vb.cpus = "1"
    end

  # INSTALL NODE, PM2, NGINX
   node.vm.provision "shell", inline: <<-SHELL
    sudo su -
    cd /var/www/
    apt-get upgrade
    apt-get install -y vim git curl build-essential openssl libssl-dev pkg-config 
    apt-get install -y software-properties-common python-software-properties
    curl -sL https://deb.nodesource.com/setup_6.x -o nodesource_setup.sh
    bash nodesource_setup.sh
    apt-get install nodejs
    npm install -g pm2
    pm2 startup systemd
    apt-get install -y nginx 
    apt-get update 
  SHELL
    
  end

# VAGRANT MESSAGE
  config.vm.post_up_message = "You're ready!"
end
