=begin
@author:  Charleston Malkemus
@date:    February 15, 2016
@app:     Nginx Server
@descriptions:
This is a bare bones web and proxy server
cpu = 15%
mem = 256

=end

# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
Vagrant.require_version ">= 1.6.0"

Vagrant.configure("2") do |config|
  config.ssh.forward_agent = true

# CONFIGURE HOSTMANAGER
# 
# manage pretty url writing
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true


  # CONFIGURE WEB SERVER (nginx)
  # 
  # set hostname, network, and aliases
    config.vm.define "web", primary: true do |web|
      web.vm.box = "nginx"
      web.ssh.username = "vagrant"
      web.vm.hostname = "nginx"
      web.vm.network :private_network, ip: '192.168.42.51'
      web.vm.network :forwarded_port, guest: 3451, host: 3451

    # SYNC FOLDERS 
    # 
    # nginx should be in /var/...
    # sync local with vm folders
      web.vm.synced_folder "web/", "/var/web/", type: "nfs"
      web.vm.synced_folder "web/config/", "/etc/nginx/sites-available/", type: "nfs"
      web.sync.host_folder = "web/"
      web.sync.guest_folder = "/var/web/"

    # PRETTY URL
    #
    # set pretty url
      web.hostmanager.aliases = %w(nginx.vm)
    
    # SET RESOURCES
    #
    # box must have min 256MB and 15% CPU
    # set provider
      web.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", "15"]
        vb.memory = "256"
        vb.cpus = "1"
      end

    # START UP NGINX
    #  
    # restart nginx on guest after up
      web.trigger.after :up do
        run_remote "sudo service nginx restart"
      end
    end
  #
  # END WEB SERVER (nginx)


# VAGRANT MESSAGE
  config.vm.post_up_message = "You're ready!"
end