=begin
@author:  Charleston Malkemus
@date:    September 13, 2017
@app:     Redis Database
@descriptions:
Building redis box

=end

# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
Vagrant.require_version ">= 1.6.0"

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-16.04"
  config.ssh.forward_agent = true

# CONFIGURE HOSTMANAGER
# 
# manage pretty url writing
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true


# CONFIGURE REDIS SERVER (redis)
# 
# set hostname, network, and aliases
  config.vm.define "redis", primary: true do |redis|
    redis.ssh.username = "vagrant"
    redis.vm.hostname = "redis"
    redis.vm.network :private_network, ip: '123.123.55.100'
    redis.vm.network :forwarded_port, guest: 6379, host: 6379

  # SYNC FOLDERS 
  # 
  # redis should be in /var/...
  # sync local with vm folders
    redis.vm.synced_folder ".", "/var/data/"

  # set pretty url
    redis.hostmanager.aliases = %w(redis)

  # SET RESOURCES
  #
  # box must have min 1GB and 25% CPU
  # set provider
    redis.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--cpuexecutioncap", "25"]
      vb.memory = "1024"
      vb.cpus = "1"
    end
     
  end

# VAGRANT MESSAGE
  config.vm.post_up_message = "Ubuntu is ready!"
end